### ISSUE TITLE
Yo can we at least get a README?

### ISSUE THREAD

**Issue by cforsythe** [BillyDaniel/Python-snake#1]
For some reason I can't see a README about what this project is going to be so I have no idea what Python-snake means

**Comment by BillyDaniel** [comment]
Not Yet.

**Comment by cforsythe** [comment]
Hey, I need a README to find out what this project will be like and so I can maybe see a link to the project scope!

**Comment by cforsythe** [comment]
Bruh, you missed the deadline!

**Comment by cforsythe** [comment]
Alright glad there’s a readme now 😊
